const fs = require('fs');
const path = require('path');
const txt = fs.readFileSync(path.join(__dirname, '..', 'Graph.txt'), 'utf8');
const content = txt.replace(/^[\s\S]*?`\n/, '').replace(/\n\s*`;\s*$/, '');
const out = '/* js/graph.js - autogenerated from Graph.txt */\nwindow.GRAPH_DEFINITION = `'+content+'`;\n';
fs.writeFileSync(path.join(__dirname, '..', 'js', 'graph.js'), out);
console.log('wrote js/graph.js, length', out.length);